on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
